#!/usr/bin/env bash
# bashscript to check for subdomains

audit_subdomain() {
    local domain=$1
    local subdomain=$2

    # If subdomain is not provided, audit default subdomains
    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        record_type=$(dig +short -t CNAME "$sub.$domain" | awk '{print length($0) ? "CNAME" : "A"}')
        destination=$(dig +short "$sub.$domain")

        echo "The subdomain $sub is a $record_type record and points to $destination"
    done
}

# Check if both domain and subdomain are provided
if [ "$#" -eq 2 ]; then
    audit_subdomain "$1" "$2"
elif [ "$#" -eq 1 ]; then
    audit_subdomain "$1"
else
    echo "Usage: $0 <domain> [<subdomain>]"
    exit 1
fi

